<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd25d6230bd03be892f53482c87b6e695
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd25d6230bd03be892f53482c87b6e695::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd25d6230bd03be892f53482c87b6e695::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd25d6230bd03be892f53482c87b6e695::$classMap;

        }, null, ClassLoader::class);
    }
}
